### ISSUE TITLE
Paste without formatting

### ISSUE THREAD

**Issue by p0deje** [p0deje/Maccy#109]
It seems like people need a way to paste with formatting being cleared. It's possible to implement a new shortcut (COMMAND+SHIFT+CONTROL+N) which will do the trick and also add an option to make it a default behavior.

Continuation of #37.

**Comment by sudo-suhas** [comment]
When I am copying between different applications, I often need to strip out the style. And this was a default behaviour I relied upon previous to the recent release. An example would be copying text from slack or code editor to google doc.

Having a different shortcut or toggle to tweak default behaviour would be great. Thanks again for making something great that I use everyday 🙂

**Comment by amod400** [comment]
> When I am copying between different applications, I often need to strip out the style. And this was a default behaviour I relied upon previous to the recent release. An example would be copying text from slack or code editor to google doc.
> 
> Having a different shortcut or toggle to tweak default behaviour would be great. Thanks again for making something great that I use everyday 🙂

Yes please have this!! most wanted feature...

**Comment by jkrenge** [comment]
Moving back to the older version as well, as I never want the format to copy. :)

**Comment by grossjohann** [comment]
After reading the description, I'm still not quite clear on the UI.  I think what I would prefer is that I use the normal hotkey to bring up Maccy, then interact with the Maccy popup to get the plain text.

When interacting with Maccy, I could imagine two ways.  One is to offer a new way to select an item.  For example, return selects the item and option-return selects it with immediate pasting.  Maybe shift-return could select the plain text version, and option-shift-return could select the plain text version with immediate pasting.

The other is to offer a toggle: While Maccy is up I hit a key combo to “put it into plain-text mode”, and all selections and pastes in that mode would select or paste the plain text.  Maybe that mode is temporary (gets reset when Maccy is brought up again), or permanent (until Maccy quits).

**Comment by p0deje** [comment]
I lean towards implementing the behavior similar to automatic pasting. There will be the checkbox to "Remove formatting by default" and then, if it's disabled, the selection would work this way:

| action | behavior |
|---------|---------|
| <kbd>Enter</kbd>, <kbd>Mouse Click</kbd>, <kbd>Cmd+n</kbd> | preserves formatting and copies item |
| <kbd>Enter</kbd>, <kbd>Shift+Mouse Click</kbd>, <kbd>Cmd+Shift+n</kbd> | removes formatting and copies item |
| <kbd>Alt+Enter</kbd>, <kbd>Alt+Mouse Click</kbd>, <kbd>Alt+n</kbd> | preserves formatting and pastes item |
| <kbd>Alt+Shift+Enter</kbd>, <kbd>Alt+Shift+Mouse Click</kbd>, <kbd>Alt+Shift+n</kbd> |  removes formatting and pastes item |

**Comment by FernandoMiguel** [comment]
`cmd+shift+n` is not reachable with one hand

what's wrong with plain old (and already implement on Office and Chrome) `cmd+shift+v` to paste without format?

**Comment by p0deje** [comment]
> what's wrong with plain old (and already implement on Office and Chrome) cmd+shift+v to paste without format?

There is nothing wrong with it, but I don't understand how Maccy would integrate with it. I guess people want to paste some previous history record without formatting, so there needs to be a single shortcut to do that.

**Comment by FernandoMiguel** [comment]
> > what's wrong with plain old (and already implement on Office and Chrome) cmd+shift+v to paste without format?
> 
> There is nothing wrong with it, but I don't understand how Maccy would integrate with it. 

it should be the default shortcut

**Comment by p0deje** [comment]
What do you mean "the default shortcut"? Do you mean Maccy should paste using "cmd+shift+v" instead of "cmd+v"?

**Comment by grossjohann** [comment]
@FernandoMiguel, I also don't see how Maccy could implement the Office and Chrome behavior.  If I understand correctly, then the Office and Chrome behavior is this:

* Select some text
* Hit `cmd-C` to copy it
* Move elsewhere
* Hit `cmd-shift-V` to paste it

With Maccy, it looks like this:

* Select some text
* Hit `cmd-C` to copy it (here, Maccy listens in the background to take note of the snippet)
* Move elsewhere
* Hit `cmd-shift-C` to bring up Maccy (from here, the Maccy UI is visible and we are using Maccy shortcuts; `cmd-shift-C` is the only global shortcut, i.e. it invokes Maccy even if Maccy is not currently visible and in focus) -- MM
* Select one of the items, say using the cursor keys -- MM
* Hit `return` to select this item -- MM
* At this point, Maccy disappears and subsequent shortcuts are either not related to Maccy, or they are the single global shortcut `cmd-shift-C` that calls up Maccy again
* Hit some key, normally `cmd-V`, but I guess Office and Chrome also support `cmd-shift-V`, to paste

If we want to make changes, we can introduce a new global shortcut (say `cmd-shift-V`) that the user can use instead of `cmd-V` to paste.  But that would clobber the existing Office and Chrome functionality.

Or we make changes to the steps marked with "MM" at the end of the line -- we can introduce new shortcuts there, or additional steps.

I guess @p0deje isn't looking to add a second global shortcut to Maccy, because global shortcuts might interfere with other programs the user has running.

**Comment by FernandoMiguel** [comment]
humm
so...
cmd+c copies with formatting 
cmd+v pastes with formatting
cmd+shift+v pastes **without** formatting

cmd+shift+c shows the list and we can have a key or submenu (like clippy did) to paste with/out formatting

but everything i was talking about, was to just using keyboard shortcuts without interacting with maccy menu

**Comment by p0deje** [comment]
How would you select an older item without interacting with maccy menu?

**Comment by grossjohann** [comment]
I think @FernandoMiguel is asking for a second global shortcut, in addition to `cmd-shift-C`.
The second shortcut could be `cmd-shift-V` and it would paste the same content that `cmd-V` would have pasted, except as plain text.

Just for the record, I prefer to avoid a second global shortcut, and go with @p0deje's suggestion.

**Comment by grossjohann** [comment]
> action 	behavior
> Enter, Mouse Click, Cmd+n 	preserves formatting and copies item
> Enter, Shift+Mouse Click, Cmd+Shift+n 	removes formatting and copies item

Both lines contain the Enter shortcut.  I think you wanted to say Shift+Enter in the second line?

**Comment by vassyz** [comment]
I paste more often without formatting than with, so this behaviour is slightly annoying. I used to use [Paste.app](https://pasteapp.io/) and the way they were handling was: click on item - paste with formatting, click + shift = paste with formatting.

**Comment by grossjohann** [comment]
@vassyz, as per https://github.com/p0deje/Maccy/issues/109#issuecomment-645283572 there will be a checkbox in the preferences, so you can make "without formatting" the default behavior.

**Comment by p0deje** [comment]
Released in 0.14.0, see preferences for more details on shortcuts.

**Comment by sudo-suhas** [comment]
Thank you 🙇 !!
