### ISSUE TITLE
[Enchancement] Ignore based on app - possible fix

### ISSUE THREAD

**Issue by georgesnow** [p0deje/Maccy#135]
Possible way to ignore copied items is based on App bundle would be to monitor Pasteboard for changes when Maccy loads (part of the code is based from https://github.com/Rawnly/Pasty) :

`NotificationCenter.default.addObserver(self, selector: #selector(onPasteboardChanged), name: .NSPasteboardDidChange, object: nil)`

Then use NSworkspace for frontmost application (focusable apps):
(after the at symbol there is zero-white space character so it would display correctly if decide to copy the code below)    

    @​objc
    func onPasteboardChanged(_ notification: Notification) {
        let runningApp = NSWorkspace.shared.frontmostApplication
        
        if runningApp?.bundleIdentifier == "com.agilebits.onepassword7" {
            NSLog("ignored 1password")
        } else {
            guard let pb = notification.object as? NSPasteboard else { return }
            guard let items = pb.pasteboardItems else { return }
            
            print(items.count)
            
            guard let item = items.first?.string(forType: .string) else { return }
            
        
        }

    }

**Comment by p0deje** [comment]
That is great. I was not aware it's possible to have a notification for pasteboard changes, so I had to use a timer and periodically check it. Because of the timer, checking frontmostApplication would not be reliable.

I think this can be done in 2 iterations:

1. Replace the timer with notification. This will already be useful.
2. Introduce a preference to customize ignored apps list.

**Comment by p0deje** [comment]
Actually, as I'm looking through Pasty code they also use timer :(

https://github.com/Rawnly/Pasty/blob/master/Pasty/AppDelegate.swift#L24-L29

**Comment by georgesnow** [comment]
Correct, sorry if that wasn’t clear. I saw you used a timer. I figured you could attach it to the polling to see the count with out capturing the sensitive data (as pasty codedid). Since at The time of checking  it could validate the app that had focus you can create set of apps to ignore. 

I tested it in the pasty code used above and it appear to work for ignoring apps.  Do you still see it worth trying?

**Comment by georgesnow** [comment]
One other thought is to set notification using  didactivateapplicationnotification and it’s partner for deactivate:

https://developer.apple.com/documentation/appkit/nsworkspace/1535049-didactivateapplicationnotification

This returns the active app as NSRunningApplication representation. Each time the active app changes Maccy could be notified what is the active app and there by disabling the timer if it matches certain app bundle. And when that app resigns(Deactives) as the active app the timer checking pasteboard turns back on.

**Comment by p0deje** [comment]
Thanks for great suggestions! My only problem with all these approaches is that it might fail in some cases. For example, when something is copied from long-running background process (e.g. bash script). Getting currently active application doesn't guarantee that pastboard is changed by it. However, I guess it might be enough in 95% of cases.

I believe the way to go is to make timer much faster (e.g. 100ms instead of current 1s) and then check for `NSWorkspace.shared.frontmostApplication`. I'll also need to build a preference pane with application selector to customize the list.

**Comment by georgesnow** [comment]
I did some testing using didActiveApplicationNotfication. I couldn't get it to work reliably. I think it is best to use the `NSWorkspace.shared.frontmostApplication`

I would just add a note where you add apps  the user wants to ignore that it will _only ignore the focused/active application_ **and not** background tasks/applications.
