### ISSUE TITLE
Feature Request:  Clear item should ask for confirmation before deleting clipboard

### ISSUE THREAD

**Issue by rochakagrawal** [p0deje/Maccy#208]
Its easy to accidentally press Clear and wipe out my clipboard. I believe it should ask for a confirmation before deleting my clipboard history items.  I have 200 items configured and it's a massive pain to lose everything with no warning with an accidental click

**Comment by p0deje** [comment]
I'm reluctant to add this as nobody ever reported this before during the past 2+ years.
Please vote on the issue with 👍/👎.

**Comment by rochakagrawal** [comment]
In that case at least pls put the “clear”menu item somewhere at the bottom or in a sub menu rather than right next to preferences menu item .  I was trying to click on preferences and ended up clearing my clipboard  :(

**Comment by p0deje** [comment]
Ah, can you try running the following command in terminal and see if it's any better for you?

```
 defaults write org.p0deje.Maccy enableSaratovSeparator true
```

**Comment by rochakagrawal** [comment]
Thanks.  What is this command for please?

**Comment by p0deje** [comment]
It should add an additional separator between Clear and Preferences.

**Comment by rochakagrawal** [comment]
Ok I tried that but it didn’t change.. there is no spaces between the two

**Comment by p0deje** [comment]
You're right, guess this feature got lost somewhere during refactoring. I'll return it in the next version.

**Comment by p0deje** [comment]
<img width="574" alt="Screen Shot 2020-11-23 at 06 18 40" src="https://user-images.githubusercontent.com/665846/99956255-bceb3a00-2d53-11eb-9843-03346f6ac738.png">

**Comment by fharper** [comment]
I came here to create this issue as I just cleared by history by accident and lost something important I can't retrieve 🤦‍♂️

I read @p0deje you are hesitant to add this, but it's not because nobody reported it that nobody cleared things by mistake. I also doubt people clear their history quite often, so one more confirmation won't make the experience really bad for folks. Lastly, if you really think having a confirmation popup will deteriorate the experience, add it as an option in the preferences, disable by default. A bit more coding, but in the end, it will save people like @rochakagrawal and me 🤣

I personally don't think a separator will help. People may clear accidentally less often, but there is still no confirmation. People are used to a confirmation when you want to delete something you cannot restore.

(By the way, I wrote a lot of things for the sake of the discussion and because I can't do a PR in the coming days - I also hate Swift- but I love your app, I tried many and stick with yours for a while now.)

**Comment by artginzburg** [comment]
I think there should be a confirmation, like in trash Bin. Cause Maccy is logically the same Bin folder, but for clipboard. When you click `Empty` in Bin, it displays the following notice:
<img width="372" alt="Screenshot 2021-01-22 at 19 06 40" src="https://user-images.githubusercontent.com/46137336/105514841-066cec80-5ce5-11eb-90d4-5cf27dc34611.png">

It would be useful to have the same warning in Maccy as a setting that is turned on by default.
> e.g. for Bin it can be configured in Finder > Preferences > Advanced > [x] Show warning before emptying the Bin
