### ISSUE TITLE
Feature request: Only show footer on menubar click

### ISSUE THREAD

**Issue by zacharykeeping** [p0deje/Maccy#235]
I like to use Maccy by setting it to pop up at screen centre, which looks much better and cleaner when the option to hide footer is selected. This gives it a somewhat similar look and functionality to other clipboard managers like PasteBot. However, hiding the footer means preferences and other options get hidden behind rather obscure shortcuts. I feel like there should be an option to only hide the footer when triggered by a shortcut so those options can still be easily accessed via the menubar icon.

One other workaround I can think of would be to have the footer hidden as per normal, but be able to access those options by right clicking on the menubar icon.

**Comment by p0deje** [comment]
Thank you for proposing this idea, but I'm not going to implement this for the following reasons:

1. Opening preferences with footer hidden is as simple as pressing CMD+,. It's not an obscure shortcut because it's used to show preferences by all native macOS applications.
2. Keeping two separate menus (one for shortcut and one for menubar) is going to complicate implementation significantly as we need to maintain 2 menus and update them simultaneously.
3. Disabling footer but still seeing it when clicking on menubar is subpar user experience (you don't see what you asked for).
4. As for implementing right-click on menu bar, it is possible to do so but I personally don't see much value in it compared to pressing CMD+,.
