### ISSUE TITLE
Clearing only sets the ZITEM field to NULL in ZHISTORYITEMCONTENT

### ISSUE THREAD

**Issue by nooproblem** [p0deje/Maccy#274]
Hi,

Firstly, thanks for this great piece of software, I really appreciate it! This issue is only raised as an observation and no criticism is implied.

I would expect that clearing would remove all the clipboard data records from the sqlite database. However, on inspecting the database, it appears that only the ZITEM field is set to NULL for all records in the ZHISTORYITEMCONTENT table. I am not sure if this is to be expected? I would be happier with this if the database could be encrypted, but as this is not currently the case it might be easier to create a script to delete all the records in the ZHISTORYITEMCONTENT table as a work around.

**Comment by p0deje** [comment]
Oh, you are right. This should definitely be fixed. The problem is that https://github.com/p0deje/Maccy/blob/master/Maccy/History.swift#L40-L43 only removes HistoryItem, but it should first iterate of item's HistoryItemContent and remove them too.

**Comment by 0f3eacd3** [comment]
I am worried that this issue may not have been resolved - I am now on Version 0.20.1 (6), but still see the previously stored content upon inspecting the database after clearing maccy.

**Comment by p0deje** [comment]
It's been fixed but not released yet. Will be available in 0.21.0.

**Comment by 0f3eacd3** [comment]
@p0deje Thanks for the info. I believe this is a security vulnerability that should be fixed and pushed promptly, this has been delayed for too long now. Also, I think a migration should be included to clean up content that was previously persisted in error.

**Comment by jacopo-j** [comment]
As I briefly mentioned in #151, I'm still experiencing this issue, although I'm not sure why it happens. If I open the database (which is at path `~/Library/Containers/org.p0deje.Maccy/Data/Library/Application Support/Maccy/Storage.sqlite`) after some hours of normal usage, I can find some deleted entries in the ZHISTORYITEMCONTENT table. However, trying to reproduce the problem is difficult, because it seems like most of the times entries are correctly deleted. I couldn't find a pattern.

It may be helpful if other users checked their database and confirmed whether they still see deleted entries in ZHISTORYITEMCONTENT.
