### ISSUE TITLE
Popup's location

### ISSUE THREAD

**Issue by imoyu** [p0deje/Maccy#346]
After using Maccy for a while, I feel most satisfied, but there are two inconveniences:
1. location where popup appears: Cursor
I want the position of the popup box to appear near the input cursor, not the attachment of the mouse cursor, because the position of the mouse cursor may be far away from the position of my input, I have to look back and forth
2. pin and clear
These two operations are not used very often. I would prefer to have a button to click to complete, because I feel that memorizing too many shortcut keys is too cumbersome, and it is difficult to remember shortcut keys for functions that are not used frequently.

In addition, I have another requirement:
Do you consider supporting multi-line pasting, because sometimes I will copy several lines of sentences from different places and paste them on the same page at the same time. Pasting one sentence by one is a bit troublesome.
Thank you for your work!

**Comment by p0deje** [comment]
> location where popup appears: Cursor
I want the position of the popup box to appear near the input cursor, not the attachment of the mouse cursor, because the position of the mouse cursor may be far away from the position of my input, I have to look back and forth

Please see #150 - let's track the work there.

> pin and clear
These two operations are not used very often. I would prefer to have a button to click to complete, because I feel that memorizing too many shortcut keys is too cumbersome, and it is difficult to remember shortcut keys for functions that are not used frequently.

I don't understand, could you please elaborate what you are missing.

> Do you consider supporting multi-line pasting, because sometimes I will copy several lines of sentences from different places and paste them on the same page at the same time. Pasting one sentence by one is a bit troublesome.

This would be able to achieve with #239, let's track the work there.

**Comment by imoyu** [comment]
For the second point, my need is to use specific buttons to pin or delete records instead of relying solely on shortcut keys. Because these two functions are not used frequently, I can't think of shortcut keys quickly,for occasional functions, I prefer to use the mouse to operate directly.

**Comment by p0deje** [comment]
So you want to pin/remove items using mouse? Can you be more specific of how this should work?

**Comment by imoyu** [comment]
For example, add a button after each item, click to select pin, remove and other operations (refer to the clipboard that comes with win10 (win + v))

**Comment by p0deje** [comment]
I agree it would be great to have pin/delete in the tooltip, but it's not possible until #267 is implemented. Closing this in favor of it.
