### ISSUE TITLE
How to manage passwords?

### ISSUE THREAD

**Issue by zifeo** [p0deje/Maccy#4]
Would it be possible to filter the passwords copied from (e.g.) 1Password?

**Comment by p0deje** [comment]
It should be possible and I've seen some ways to do that https://github.com/p0deje/dotfiles/blob/7d5f426446965e9dc8b8aca4059486a558e9ca30/.hammerspoon/clipboard.lua#L59-L64.

I'm not sure when I'll be able to implement it as I'm busy at work, so PRs are more than welcome.

**Comment by p0deje** [comment]
In 0.3.2, Maccy will respect password managers and, if they remove copied password from the clipboard, Maccy will remove it from the history too. This will however only work when for the last item in history, so if you copy the password and then copy something else, the password will stay in history. I'm not sure if there is any way to solve this problem because I see no way to distinguish between "password" and "usual text".
