### ISSUE TITLE
Scroll through my clipboard

### ISSUE THREAD

**Issue by FishBKK4** [p0deje/Maccy#414]
I love Maccy and use it abundantly. 
The clipboard I have set to keep 200 items but when I click on the Maccy icon, only the 15 latest show up and there is no way for me to scroll and see the ones older than that.
I know I can search but when I make a lot of copies of things (to paste later) I don't always remember the contents, hence scrolling through them would help a lot. 
Is there a way to see all the history?

**Comment by p0deje** [comment]
Sure, just set menu size to 0 in the Appereance preferences. <img width="613" alt="Screen Shot 2022-06-09 at 09 15 02" src="https://user-images.githubusercontent.com/665846/172895035-fff4a4fe-e865-424f-a56f-39d08988330a.png">

**Comment by notsatyarth** [comment]
Hey there , thank you for the really great app here :). 
I was wondering if it would be possible to have both? i.e. have a "window" of 10 visible and allow a scroll within that window size. Right now, if I set menu size to 0, then the maccy window occupies the entire screen due to the large number of items in history (I've kept mine at 999)
