### ISSUE TITLE
Localizing maccy.app website

### ISSUE THREAD

**Issue by fabifabulousity** [p0deje/Maccy#423]
I would love to help translating the maccy.app website into German. Can you provide the text strings? ☺️

**Comment by p0deje** [comment]
There aren't localization files - it's just https://github.com/p0deje/Maccy/blob/gh-pages/index.html here. I'm not sure how the website should be translated, but if you can copy the file and just replace all text inside with German - I'll figure out the rest.

**Comment by fabifabulousity** [comment]
![Bildschirmfoto 2022-06-20 um 23 09 41](https://user-images.githubusercontent.com/72652159/174680003-5cd48540-dfe2-4df1-8487-0724e6ed460f.jpg)

I created a pull request. I also translated the "how to" graphic, but it needs to be recreated with the correct font.

**Comment by p0deje** [comment]
Thank you for the proposal, but after thinking a lot about localizations, I've come to the conclusion it's going complicate things more than benefit. The current state of Maccy itself with support for 13 languages makes it very hard for me to implement even simple UI changes (e.g. #436) because I need to make sure it's properly localized everywhere. Even though Xcode provides some tools to simplify it, it's nevertheless a lot of work and the quality is poor for languages I don't speak fluently as I have to resort to Google Translate for them. Extending localizations to the website and images will make things even more complex for me. Unless there is a way to streamline the localization, I would prefer to focus on building new features and improving the stability of the app. I would be happy to get back to this, but I simply don't have time now. Sorry that your efforts in this issue turned out to be in vain.
