### ISSUE TITLE
Add Launch at Login feature

### ISSUE THREAD

**Issue by patricks** [p0deje/Maccy#5]
A launch at login feature would be nice.

**Comment by p0deje** [comment]
Why don't you just add Maccy to your "Login Items"?

**Comment by patricks** [comment]
I know that this would be possible, but a feature like other apps provide ist, would be nice 😉

**Comment by p0deje** [comment]
In order to make it work, I have to implement:

1. a launcher application that allows registering Maccy as a login application (like [this](https://theswiftdev.com/2017/10/27/how-to-launch-a-macos-app-at-login/)) or pull in [dependency](https://github.com/sindresorhus/LaunchAtLogin)
2. create a new settings window where this should be configured

For a person like me who is still not good at Mac app development, it's simply too much work compared to the user doing just a few clicks to add Maccy to login item. I'll be happy to accept PRs implementing ☝️ but I don't see myself working on this in the nearest future.

**Comment by jaredreich** [comment]
@p0deje What's wrong with pulling in `sindresorhus`'s https://github.com/sindresorhus/LaunchAtLogin dependency? I would argue that this feature is absolutely mandatory. Nobody wants to manually add/remove their login items from within system preferences. This alone made me instantly delete the app.

Cool project though, and good work so far!

**Comment by p0deje** [comment]
Reopening this for the future. It's low priority for me, but I'll happily merge PR adding the support.

**Comment by georgesnow** [comment]
https://medium.com/@hoishing/adding-login-items-for-macos-7d76458f6495

this is similar to the GitHub repo posted above. this one I think looks a bit simpler.

**Comment by DaFuqtor** [comment]
I personally prefer using [Clipy/LoginServiceKit](//github.com/Clipy/LoginServiceKit) instead of [sindresorhus/LaunchAtLogin](//github.com/sindresorhus/LaunchAtLogin), because it allows the user to control the setting (which was set in the app) from the default System Preferences later.
I just like to use the built-in features.
