### ISSUE TITLE
Exclude password mangers input from showing

### ISSUE THREAD

**Issue by mualhadi** [p0deje/Maccy#53]
Can we have the option to exclude password managers (Lastpass or 1Password) input from showing on the Maccy app. while still being on the clipboard of course

**Comment by p0deje** [comment]
As far as I know, It's not possible to distinguish which app copied something to clipboard, so there is no way to understand if it was password manager.

However, typically password managers remove the password from clipboard after a period of time (e.g. 1 minute). If this happens, Maccy also removes it from its history. This only works if the password is the most recent copied item. Otherwise, you can remove it manually use Option+Delete.
