### ISSUE TITLE
MacOS - More security in Ignore feature for Keychain items

### ISSUE THREAD

**Issue by tonewarper** [p0deje/Maccy#541]
A common activity is the manual copying from Keychain of forgotten Safari-generated passwords for various website credentials saved to there, then pasting them manually into a login form field, especially when one has changed browsers, sessions, or devices. But if one adds Keychain to the Ignore list, significant usability/benefit of Maccy is lost because such passwords do not get conveniently copied. If kept in history however, one runs a high risk of such being sniffed. It would be a logical security compromise for Mac users that Maccy DOES copy Keychain items, but DOES NOT remember them in history -- or erases from memory Keychain-originated items after a certain time. Maccy is, after all, a Mac-focused clipboard manager.

**Comment by p0deje** [comment]
I don't understand what is required here. If Maccy keeps a track of copied password from Keychain for later usage, how would Maccy not keep them in history? Can you please provide few concrete examples how you would use it?

**Comment by tonewarper** [comment]
> 

Sure. The more I think about this, the more I think it doesn't have to do anything with Ignore preferences. for example, because passwords are a higher-risk text-type, Maccy might --by default as a fixed standard, or optionally configured to do so in preferences-- override the number of history notes to remember when it copies content from Keychain. So they won't persist in memory 2, 20, 200 notes ago, but only the most recent note. Or even a fraction of a note, for example for 1-5 minutes and then be purged (that's plenty of time for someone to paste elsewhere the credentials that they looked up in Keychain). Or/and content of this type in Maccy's Menu Bar drop-down listing could be flagged as high-risk content with exclamat!ons / different color/bolded to stand out to the user to pay attention and manually delete them. Or it could be another level in the implementation of Ignore, where there isn't just an allow/block list but also a red-listing for need-to-copy content that is dangerous and handled more carefully. As an analogy: Simple free academic firewalls block or open ports; but those that are used properly day-to-day, also give you granular control like inspection, filtering, and sandboxing of packets. Nothing (other than your MUCH appreciated dev time!) prevents a clipboard manager from adopting similar logic. And if it is made to work for Keychain, then it can extend to other password-management apps and sensitive content-types like credit card numbers.

**Comment by p0deje** [comment]
Ok, I see how this can be valuable but the use cases vary so much that it would require many preferences for fine-tuning. 

> Maccy might --by default as a fixed standard, or optionally configured to do so in preferences-- override the number of history notes to remember when it copies content from Keychain. So they won't persist in memory 2, 20, 200 notes ago, but only the most recent note.
Or even a fraction of a note, for example for 1-5 minutes and then be purged (that's plenty of time for someone to paste elsewhere the credentials that they looked up in Keychain).

For example, 1-5 minutes for keeping Keychain.app is too arbitrary and might be too little / too much depending on the context. It's also not clear how it should work for pinned items, whether it should still remove it after the time passed or not. 

> Or/and content of this type in Maccy's Menu Bar drop-down listing could be flagged as high-risk content with exclamat!ons / different color/bolded to stand out to the user to pay attention and manually delete them.
Or it could be another level in the implementation of Ignore, where there isn't just an allow/block list but also a red-listing for need-to-copy content that is dangerous and handled more carefully.

I would see this as a problem because it would deliberately highlight the sensitive content in the list. Given the attacker has even short access to the computer, he can easily find all confidential data or extract it from video recording / screenshot.

Moving on, recent macOS provide "Password" application that is a part of System Settings - it is used to copy user names / passwords and there is no way to identify passwords copied from there (like Keychain). 

With an amount of work needed here, I'm not convinced it's valuable enough at the moment.

**Comment by p0deje** [comment]
Closing since there is nothing I can do here. Feel free to re-open and continue discussion.
