### ISSUE TITLE
unable to paste text in whatsapp 

### ISSUE THREAD

**Issue by avichou** [p0deje/Maccy#547]
macOS ventura 13.3.1
macbook air m1 
whatsapp beta 

https://github.com/p0deje/Maccy/assets/86660671/232f51c5-9cb8-4496-95a2-3e0faa68b3f7

video showing the issue below

**Comment by Slackadays** [comment]
Did you enable these two settings?

```
Why doesn't it paste when I select an item in history?
1. Make sure you have "Paste automatically" enabled in Preferences.
2. Make sure "Maccy" is added to System Settings -> Privacy & Security -> Accessibility.
```

**Comment by avichou** [comment]
> Did you enable these two settings?
> 
> ```
> Why doesn't it paste when I select an item in history?
> 1. Make sure you have "Paste automatically" enabled in Preferences.
> 2. Make sure "Maccy" is added to System Settings -> Privacy & Security -> Accessibility.
> ```

boh of these are enabled 

actually i probably shouldn't annoy you with that , since it works on any other apps but whatsapp, must be a whatsapp issue

**Comment by p0deje** [comment]
There is a problem with the WhatsApp application - it loses focus on the message text field when you cmd+tab from the app and back to it. Due to the same issue, Maccy cannot properly paste into it. As a temporary workaround, you can enable "Avoid taking application focus" in the "Advanced" section of the Maccy preferences. Then, pasting works when you paste by selecting an item using Enter key in Maccy, but it still doesn't work when selecting using shortcuts and mouse.

**Comment by avichou** [comment]
> There is a problem with the WhatsApp application - it loses focus on the message text field when you cmd+tab from the app and back to it. Due to the same issue, Maccy cannot properly paste into it. As a temporary workaround, you can enable "Avoid taking application focus" in the "Advanced" section of the Maccy preferences. Then, pasting works when you paste by selecting an item using Enter key in Maccy, but it still doesn't work when selecting using shortcuts and mouse.

thank you and thanks for this wonderful app 

shall i close the issue ?

**Comment by p0deje** [comment]
Yes, there is not so much I can do about it. Closing!

**Comment by avichou** [comment]
> Yes, there is not so much I can do about it. Closing!

latest release of maccy...or whatsapp? fixed it ! cheers
