### ISSUE TITLE
Allow using delete instead of option+delete

### ISSUE THREAD

**Issue by pranavmittal611** [p0deje/Maccy#583]
First of all, thanks a lot for creating Maccy, it is so much better than any other such tools I've tried.

I have a small feature request, can an option be created in the preferences that, when checked, allows deleting the selected entry using only the `delete` key instead of `option+delete`?
I am used to the clipboard manager in Windows and pressing the `option` key again and again is slightly cumbersome.

Also, can the total number of clipboard items be shown in the footer, maybe inside a bracket after the clear option?
For example - "Clear (48 items)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;⌘⌥⌫"

Thanks a lot.

**Comment by p0deje** [comment]
Currently, delete will remove the last character from a search field. Because removing history is a destructive action that can't be recovered from, I think it should not be bound to a simple key press.

If you find yourself removing too much - maybe you need to configure ignore lists accordingly. 

As for the counter, I'll add it.

**Comment by pranavmittal611** [comment]
The conflict with the search bar is a valid point, I have disabled it for now but it's for sure a handy feature.

Thanks for the consideration. Will have to get used to `option+delete`.

**Comment by p0deje** [comment]
Even when the search is hidden, you can still use it by typing words.
