### ISSUE TITLE
"clear" not working

### ISSUE THREAD

**Issue by thewisenerd** [p0deje/Maccy#59]
<img width="310" alt="Screen Shot 2019-10-27 at 22 54 37" src="https://user-images.githubusercontent.com/2658885/67638642-d7fb3880-f90c-11e9-82cb-4d6409d527fd.png">

The "clear" button does call `Menu.clear` but the HistoryMenuItem still remains in the menu.
I have to restart the application in order to get the menu cleared.

Copying something else also does weird behavior, like in the attached screenshot.

version: 0.6.0 from homebrew
macOS: catalina

**Comment by thewisenerd** [comment]
this "works", not sure if correct though:

in `Menu.swift`
```diff
   func clear() {
+    for item in historyItems {
+        removeItem(item)
+    }
     historyItems.removeAll()
   }
```

**Comment by thewisenerd** [comment]
also, I noticed that we have one NSMenu and historyItems is inserted into it; if we want to implement #26 or #40, we should ideally have history as a separate "submenu" so we can call `NSMenu.removeAll()`?
disclaimer: I am not aware of Swift or AppKit conventions, so, :salt:

**Comment by p0deje** [comment]
Thanks for the bug report and the proposed fix!

> also, I noticed that we have one NSMenu and historyItems is inserted into it; if we want to implement #26 or #40, we should ideally have history as a separate "submenu" so we can call NSMenu.removeAll()?

I am not sure if submenu works in this case as it might be shown as a single item that expands to submenu items when hovered (e.g. on screenshot)
![Screenshot 2019-10-28 at 13 01 07 ](https://user-images.githubusercontent.com/665846/67658176-0ae01380-f983-11e9-807e-09b8017b16e0.png)

 Otherwise, If that's not true, I think it's a great idea that will simplify things so much.
