### ISSUE TITLE
A few things I would love to see added to Maccy

### ISSUE THREAD

**Issue by spaceprograms** [p0deje/Maccy#656]
Hi, thanks for creating Maccy - I love it so far. However, there are a couple of things I wish you would add to the software. I used to use ClipMenu many years ago and it had a some really useful features that I think Maccy would also benefit from.

1. It would be good if you could put your pinned items into folders to save space at the top of the menu and to group related items together.
2. Would it be possible to run custom scripts from Maccy? For example I often have to paste todays date into a text file and I use an Applescript to this at the moment.
3. Could you include options to change case while pasting the text using a modifier key to bring up a menu with case options?

**Comment by p0deje** [comment]
Thank you for sharing the feedback, please see my replies below;

> It would be good if you could put your pinned items into folders to save space at the top of the menu and to group related items together.

Can you read through and add more details why this is needed in #307? 

> Would it be possible to run custom scripts from Maccy? For example I often have to paste today's date into a text file and I use an Applescript to this at the moment.

This is more of a snippet / text expansion application requirement rather than a clipboard manager. I believe there are apps out there that can help you do that.

> Could you include options to change case while pasting the text using a modifier key to bring up a menu with case options?

You can implement this by yourself via Shortcuts:

1. Create a custom workflow in shortcut that runs on a key press.
2. It would take the selected item from Maccy.
3. Show a menu with case conversion options.
4. Upon selection, it would convert the copied text from Maccy
5. Finally paste it.

You can see some examples of using Shortcuts in https://www.reddit.com/r/macapps/comments/11sxz5t/maccy_026/. Feel free to ask any questions here and I'll help.

**Comment by spaceprograms** [comment]
Hi Alex,Thanks for your message and for your consideration of my requests.The reason I would like folders to hold pinned items is for example: 1 to hold a list of email addresses, 2 to hold some common used texts for email replies.Doing this groups these pinned items together, rather than having a big list of them pinned at the top.I hope this makes sense?Sent from my iPhoneOn 25 Oct 2023, at 3:28 pm, Alex Rodionov ***@***.***> wrote:﻿
Thank you for sharing the feedback, please see my replies below;

It would be good if you could put your pinned items into folders to save space at the top of the menu and to group related items together.

Can you read through and add more details why this is needed in #307?

Would it be possible to run custom scripts from Maccy? For example I often have to paste today's date into a text file and I use an Applescript to this at the moment.

This is more of a snippet / text expansion application requirement rather than a clipboard manager. I believe there are apps out there that can help you do that.

Could you include options to change case while pasting the text using a modifier key to bring up a menu with case options?

You can implement this by yourself via Shortcuts:

Create a custom workflow in shortcut that runs on a key press.
It would take the selected item from Maccy.
Show a menu with case conversion options.
Upon selection, it would convert the copied text from Maccy
Finally paste it.

You can see some examples of using Shortcuts in https://www.reddit.com/r/macapps/comments/11sxz5t/maccy_026/. Feel free to ask any questions here and I'll help.
