### ISSUE TITLE
Cannot paste with the shortcuts - M2 on Sonoma 14.2.1

### ISSUE THREAD

**Issue by occand2024** [p0deje/Maccy#703]
### Before Submitting Your Bug Report

- [X] I have verified that there isn't already an issue reporting the same bug to prevent duplication.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Maccy Version (see 'About' window)

0.29.3

### macOS Version

14.2.1

### Description

None of the ⌘ + number shortcuts work. I can select and paste from the app. However, I'd like to paste with the shortcuts only.

**Comment by p0deje** [comment]
There is no way to paste without opening Maccy first by design.

**Comment by occand2024** [comment]
I appreciate your prompt response. 

Maccy is open. Something is blocking the paste through the shortcuts such as command + 1. I can go to the tool, select the item and it pastes. It's just the shortcut, which is the critical value of the product.

**Comment by p0deje** [comment]
Please record a video showing the problem.

**Comment by occand2024** [comment]
Here you go, hope this helps: [https://www.loom.com/share/78984f74c6f04fd4990bc5c7ecc2c3f6?src=composer ](https://www.loom.com/share/78984f74c6f04fd4990bc5c7ecc2c3f6?src=composer)

**Comment by p0deje** [comment]
@occand2024 Thank you for a thorough explanation - I'll do my best to match it.

First of all, Maccy can only paste using ⌘1, ⌘2 etc when it is **visible**. This means you need to pop it up by clicking on a menubar icon or pressing ⌘⇧C (can be changed in Maccy preferences). Once the pop-up is shown, you can use shortcuts to paste. Also, make sure you have "Paste automatically" enabled in Maccy preferences, other it will not paste, but just place the selected item in the system clipboard.

Still, if you'd like to have global shortcuts for pasting, you can add them by using Shortcuts.app. Maccy provides a way to automate certain actions via. For example, to paste the second item via the global shortcut ⌘⇧2, you create the following workflow - https://www.icloud.com/shortcuts/8e49001d007c4dbe9a563bffea618247:

<img width="1015" alt="Screenshot 2024-01-12 at 08 55 06" src="https://github.com/p0deje/Maccy/assets/665846/0c757ecd-805a-4a49-86f7-88414d9c03c0">

Similarly, you can create separate workflows for item 3, 4, etc.

The reason ⌘1, ⌘2 are not global shortcuts is because they would conflict with many applications. For example, Safari takes these keys to switch to the first, second, etc tab. Maccy should not overwrite those.
