### ISSUE TITLE
Popup position

### ISSUE THREAD

**Issue by arnotae** [p0deje/Maccy#76]
Is it possible to always open the popup in the center of the screen (not following the mouse) ?

**Comment by p0deje** [comment]
It's easy to pop it up in the center meaning that the _top left_ corner of the window will be in center. Is that what you are looking for?

**Comment by arnotae** [comment]
Exactly, I think the popup position should be like `X = centerX - (popupWidth/2)` and `Y = centerY`

**Comment by timharris777** [comment]
I would also like this feature. The way it follows the mouse is kind of annoying. I would prefer it to always popup centered on the screen. Similar to spotlight.

**Comment by timharris777** [comment]
Maybe setting this as a property so that it can be customized by the user.

**Comment by p0deje** [comment]
It should not be hard to add this feature, but I can't promise to implement it soon as I'm swamped at work. If anyone wants to give it a shot, you will need to change https://github.com/p0deje/Maccy/blob/master/Maccy/Maccy.swift#L87 so that instead of `NSEvent.mouseLocation` it would use the center of the screen.

**Comment by arnotae** [comment]
Thanks @p0deje 👍
