### ISSUE TITLE
Option to add custom templates that can be pasted anytime

### ISSUE THREAD

**Issue by laraib07** [p0deje/Maccy#781]
### Before Submitting Your Feature Request

- [X] Check that there isn't already a similar feature request to avoid creating a duplicate.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Problem

Add an option to add custom templates that can be pasted anytime.
For example: email templates you need often, or chatgpt prompts, etc

**Comment by p0deje** [comment]
I feel like this is more of a snippet manager feature than a clipboard manager one. I always tried to avoid mixing these two in Maccy because I believe there are great snippet managers out there already. So for now, I will close this issue. Feel free to re-open and provide your perspective if you disagree.
