### ISSUE TITLE
Edit text

### ISSUE THREAD

**Issue by Alrazzouq** [p0deje/Maccy#792]
### Before Submitting Your Feature Request

- [X] Check that there isn't already a similar feature request to avoid creating a duplicate.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Problem

Hi... Could you add an option to edit the copied text.

**Comment by p0deje** [comment]
@Alrazzouq  Sorry, but I believe that's too much for a clipboard manager application.

**Comment by timbaileyjones** [comment]
@p0deje - normally I would agree with you, but I have a need to edit what gets saved too.  I just finished a job search, and most of my use of Maccy revolved around cutting and pasting canned responses to recruiters (multi-line strings maybe 1k-2k in size).

The trouble is that what I "copy" from Linkedin-within-chrome got saved with too much additional whitespace and newlines.  While I realize that this is probably because of LinkedIn's rendering of my conversations in the LinkedIn chat window, the extra newlines get pasted into the chat windows of other recipients when I select and paste.  

Side note: I've had a devil of a time finding a tool that will let me edit the ZITEMHISTORY.ZTITLE field in the Storage.sqlite file. I've tried 3 vscode sqlite-database plugins, plus a standalone app called 'DB Browser for SQLite'.  Like Maccy itself, they all show me the beginning and end of my items, but with '...' in the middle.  I was expecting a multi-line editing window with the full text visible.

A simpler workaround might be a configuration checkbox that enables newly-copied clipboard items to have `trim()` and `replace('[\n\r]', '', 'g')` run on them prior to being saved.  Would you consider this solution?   @Alrazzouq didn't mention how he wanted to edit his text, but this would fix my problem.

For now, my workaround is paste into MacVim, use it to clean up all of LinkedIn's extra whitespace garbage, do a select all, and have Maccy copy from there.  Then I can pin the item copied from MacVim.

**Comment by p0deje** [comment]
@timbaileyjones You could probably automate all of that via the Shortcuts.app. Just create a new workflow that receives selected text as input (you likely need to make it available via services menu), then cleanup all extra whitespace using "Replace Text" and finally copy it to the system clipboard using "Copy to Clipboard".

**Comment by Alrazzouq** [comment]
I believe that simple editing will be very helpful.

**Comment by olfway** [comment]
I also often want to edit entry before pasting in in terminal as a command

Right now I have to copy some entry, then switch / start some other app (It should be something small), edit then copy and only after that paste in terminal

**Comment by p0deje** [comment]
Why not paste and then edit inside Terminal? How would editing in Maccy make things easier?

**Comment by p0deje** [comment]
Why don't you paste into Terminal window and then just edit directly there w/o Vim or anything else? Paste, press Ctrl-U multiple times and so on

**Comment by olfway** [comment]
Because shell will start executing commands if I have newlines in pasted text

**Comment by p0deje** [comment]
Ok, I normally use iTerm which strips off the trailing newline to prevent execution right away. Does your terminal application have such a feature?

**Comment by olfway** [comment]
I use both Term and iTerm for different purposes
But in my example I have part of prompt, command and several lines of output
It will not help if just trailing new line will be stripped

**Comment by p0deje** [comment]
If the trailing newline is removed, you can then paste into a terminal and edit it directly inside it.

**Comment by olfway** [comment]
No, I can't
For example my clipboard text:
```
user@host:/path $ date
Thu Dec  5 16:26:02 UTC 2024
```
(two lines, no newline at the end of last line)

If I paste it I get:
```
# user@host:/path $ date
Thu Dec  5 16:26:02 UTC 2024
bash: user@host:/path: No such file or directory
bash: Thu: command not found
#
```

**Comment by p0deje** [comment]
<img width="406" alt="Screenshot 2024-12-05 at 22 15 01" src="https://github.com/user-attachments/assets/e5c65b29-10d5-4838-aab9-53aa0a864fe3">

I use iTerm and it pastes as a multiline text, not sure if the settings needs to be adjusted.

**Comment by olfway** [comment]
Actually it depends on shell
In bash 5.1 it works:
```
bash-5.1# user@host:/path $ date
Thu Dec  5 16:26:02 UTC 2024^C
bash-5.1#
```

and in 5.0 it doesn't:
```
bash-5.0# user@host:/path $ date
bash: user@host:/path: No such file or directory
bash-5.0# Thu Dec  5 16:26:02 UTC 2024^C
```

Anyway, I can run vim / cat in terminal or paste in some editor.
I just wanted to mention that I need to edit before paste quite often
