### ISSUE TITLE
The history doesn't clean completely

### ISSUE THREAD

**Issue by yarinl3** [p0deje/Maccy#809]
### Before Submitting Your Bug Report

- [X] I have verified that there isn't already an issue reporting the same bug to prevent duplication.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Maccy Version (see 'About' window)

1.0.0

### macOS Version

15 Beta 3

### Maccy Settings

```Shell
{
    "KeyboardShortcuts_delete" = "{\\"carbonModifiers\\":2048,\\"carbonKeyCode\\":51}";
    "KeyboardShortcuts_pin" = "{\\"carbonModifiers\\":2048,\\"carbonKeyCode\\":35}";
    "KeyboardShortcuts_popup" = "{\\"carbonModifiers\\":768,\\"carbonKeyCode\\":9}";
    "LaunchAtLogin__hasMigrated" = 1;
    "NSStatusItem Visible Item-0" = 0;
    "NSWindow Frame SUStatusFrame" = "664 731 400 134 0 0 1728 1079 ";
    "NSWindow Frame com.sindresorhus.Preferences.FrameAutosaveName" = "607 290 442 493 0 0 1728 1079 ";
    "NSWindow Frame com.sindresorhus.Settings.FrameAutosaveName" = "594 609 442 322 0 0 1728 1079 ";
    SUEnableAutomaticChecks = 0;
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2023-07-02 05:46:21 +0000";
    SUSendProfileInfo = 0;
    enabledPasteboardTypes =     (
        "public.file-url",
        "public.tiff",
        "public.png",
        "public.utf8-plain-text",
        "public.html",
        "public.rtf"
    );
    historySize = 999;
    ignoredPasteboardTypes =     (
        "Pasteboard generator type",
        "com.agilebits.onepassword",
        "de.petermaurer.TransientPasteboardType",
        "net.antelle.keeweb",
        "com.typeit4me.clipping"
    );
    maxMenuItemLength = 100;
    menuIcon = clipboard;
    migrations =     {
        "2020-04-25-allow-custom-ignored-types" = 1;
        "2020-06-19-use-keyboardshortcuts" = 1;
        "2020-09-01-ignore-keeweb" = 1;
        "2021-02-20-allow-to-customize-supported-types" = 1;
        "2021-06-28-add-title-to-history-item" = 1;
        "2021-10-16-remove-dynamic-pasteboard-types" = 1;
        "2022-08-01-rename-suppress-clear-alert" = 1;
        "2022-11-14-add-html-rtf-to-supported-types" = 1;
        "2023-01-22-add-regexp-search-mode" = 1;
    };
    pasteByDefault = 1;
    showInStatusBar = 0;
    showRecentCopyInMenuBar = 0;
}
```

### Description

When I delete the history of the clipboard it clears the list, but history still exists in memory in files:
'/Users/xxxx/Library/Containers/org.p0deje.Maccy/Data/Library/Application Support/Maccy/Storage.sqlite-wal'
'/Users/xxxx/Library/Containers/org.p0deje.Maccy/Data/Library/Application Support/Maccy/Storage.sqlite'

<img width="694" alt="image" src="https://github.com/p0deje/Maccy/assets/74721108/9b905fbf-d91b-4e6d-9d1f-7a7fcb4767cc">

**Comment by p0deje** [comment]
That's expected, you have to quit Maccy for changes to be committed.

**Comment by Buggy-McBugFace** [comment]
The bug exists with a fresh install of Maccy version 1.0.0 (31) on a new Mac, installed via Homebrew. Despite using the "Clear" option and restarting Maccy multiple times, clipboard items are removed from the menu but the data remains in Storage.sqlite and Storage.sqlite-wal (you could omit the -o option from grep in order to see the actual data from the clipboard copies, with the caveat that the binary output might mess up your terminal session):

```
:Maccy % pwd
/Users/user/Library/Containers/org.p0deje.Maccy/Data/Library/Application Support/Maccy
:Maccy %  grep -oai rumble.com Storage.sqlite | wc -l
      13
:Maccy %  grep -oai rumble.com Storage.sqlite-wal | wc -l 
     735
```

PS: Relatedly, It would also be advisable to set the NSURLIsExcludedFromBackupKey attribute to true on the Maccy folder to exclude it from Time Machine backups. This practice is standard for unencrypted files or directories that might end up storing private data (in practice), like plaintext passwords. Many apps do this.

PPS: I noticed this Clear issue years ago on a different Mac and intended to report it but never got around to it. Apologies for the delay—luckily I remembered it now when I found myself looking for a clipboard manager again.

**Comment by p0deje** [comment]
@Buggy-McBugFace Once you quit Maccy it should clear the `sqlite` file, while `sqlite-wal` remains with a log of what was changed. I'm still unaware of how to make it cleared - see https://github.com/p0deje/Maccy/issues/608

**Comment by TOM720** [comment]
I have the same problem， only be manually deleted Storage.sqlite file，quit not work
